- name: configuring the payment module
  hosts:  payment
  become:  yes
  tasks:  
    
    - name: Installing Python3 and pip
      ansible.builtin.package:
        name:
          - python3
          - gcc
          - python3-devel
        state: present


    - name: create roboshop bultin user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        system: true
        home: /app

    - name: create a directory if it is not available
      ansible.builtin.file:
        path: /app
        state:  directory

    - name: downloadpaymentfile
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
        dest: /tmp/payment.zip

#this module thinks file exits on ansible control server,needs to extract on to remote machine
#remote_src: yes means files already exist in catalogue server
    - name: extractpaymentcode
      ansible.builtin.unarchive:
        src: /tmp/payment.zip
        dest: /app
        remote_src: yes



    - name: installing python dependiecs module
      ansible.builtin.command: pip3 install -r requirements.txt
      args:
        chdir:  /app

    - name: copy the payment service
      ansible.builtin.copy:
        src: payment.service
        dest: /etc/systemd/system/payment.service

    - name: just for reload
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: start and enable payment
      ansible.builtin.service:
        name: payment
        state: started
        enabled: yes
  
    