- name: Configure Payment Service for RoboShop
  hosts: payment
  become: yes

  vars:
    cart_host: "cart.chinni.fun"
    user_host: "user.chinni.fun"
    rabbitmq_host: "rabbitmq.chinni.fun"

  tasks:

    - name: Install Python 3 and development tools
      ansible.builtin.package:
        name:
          - python3
          - gcc
          - python3-devel
        state: present

    - name: Create roboshop system user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        system: yes
        home: /app
        comment: "roboshop system user"

    - name: Create /app directory
      ansible.builtin.file:
        path: /app
        state: directory
        owner: roboshop
        group: roboshop
        mode: '0755'

    - name: Download payment code zip
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
        dest: /tmp/payment.zip

    - name: Extract payment code into /app
      ansible.builtin.unarchive:
        src: /tmp/payment.zip
        dest: /app
        remote_src: yes
        owner: roboshop
        group: roboshop

    - name: Install Python dependencies for payment service
      ansible.builtin.command: pip3 install -r requirements.txt
      args:
        chdir: /app

    - name: Create systemd unit file for payment service
      ansible.builtin.copy:
        dest: /etc/systemd/system/payment.service
        content: |
          [Unit]
          Description=Payment Service

          [Service]
          User=root
          WorkingDirectory=/app
          Environment=CART_HOST={{ cart_host }}
          Environment=CART_PORT=8080
          Environment=USER_HOST={{ user_host }}
          Environment=USER_PORT=8080
          Environment=AMQP_HOST={{ rabbitmq_host }}
          Environment=AMQP_USER=roboshop
          Environment=AMQP_PASS=roboshop123
          ExecStart=/usr/local/bin/uwsgi --ini payment.ini
          ExecStop=/bin/kill -9 $MAINPID
          SyslogIdentifier=payment

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd daemon
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Enable and start payment service
      ansible.builtin.service:
        name: payment
        state: started
        enabled: yes
