- name: disbaling node js
  hosts: user
  become: yes
  tasks:
  - name: disbaling default node js
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs 
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create roboshop bultin user
    ansible.builtin.user:
      name: roboshop
      shell:  /sbin/nologin
      system: true
      home: /app

  - name: create a directory if it is not available
    ansible.builtin.file:
      path: /app
      state:  directory

  
  - name: download user file
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip

#this module thinks file exits on ansible control server,needs to extract on to remote machine
#remote_src: yes means files already exist in user server
  - name: extract user code
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: Install packages based on package.json.
    community.general.npm:
      path: /app

  - name: copy the mongo service
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: just for reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable user
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes
  
  